export default[
	{idE: "1", name: "ECOSISTEMA AVANZADO DE MATERIALES Y ELECTRÓNICA"},
	{idE: "2", name: "ECOSISTEMA DE LA CIENCIA DE LA VIDA"},
	{idE: "3", name: "ECOSISTEMA DE TECNOLOGÍAS DE LA INFORMACIÓN Y LA COMUNICACIÓN"},
	{idE: "4", name: "ECOSISTEMA ENERGETICO"},
	{idE: "5", name: "ECOSISTEMA CLEANTECH"}
];