export default [
	{idE: "1", idC:"1", idKET: "1", name: "ELECTRÓNICA IMPRESA Y FLEXIBLE"},
	{idE: "1", idC:"1", idKET: "2", name: "CELULAS SOLARES DE PELÍCULA / OPV"},
	{idE: "1", idC:"1", idKET: "3", name: "MATERIALES DE ILUMINACIÓN DEL ESTADO SÓLIDO (SSL), ÓPTICOS NO LINEALES, OPTOELECTRÓNICOS Y FOTÓNICOS"},
	{idE: "1", idC:"1", idKET: "4", name: "TRANSISTORES MOLECULARES"},
	{idE: "1", idC:"1", idKET: "5", name: "SISTEMAS MICRO ELECTROMECÁNICOS (MEMS)"},
	{idE: "1", idC:"1", idKET: "6", name: "POLIMEROS CONDUCTIVOS"},
	{idE: "1", idC:"1", idKET: "7", name: "METALES TECNOLOGICOS"},
	{idE: "1", idC:"2", idKET: "1", name: "MATERIALES NANOPOROSOS"},
	{idE: "1", idC:"2", idKET: "2", name: "NANOCOMPUESTOS"},
	{idE: "1", idC:"2", idKET: "3", name: "NANOTUBOS DE CARBON (CNTs)"},
	{idE: "1", idC:"2", idKET: "4", name: "GRAFENO"},
	{idE: "1", idC:"2", idKET: "5", name: "COMPONENTES ELECTROMECÁNICOS"},
	{idE: "1", idC:"2", idKET: "6", name: "ALMACENAMIENTO DE DATOS"},
	{idE: "1", idC:"2", idKET: "7", name: "NANOCABLES"},
	{idE: "1", idC:"2", idKET: "8", name: "NANOCELULOSA"},
	{idE: "1", idC:"3", idKET: "1", name: "ALEACIONES Y POLIMEROS BIOCOMPATIBLES"},
	{idE: "1", idC:"3", idKET: "2", name: "SOPORTE DE TEJIDO Y POLÍMEROS DE REGENERACIÓN"},
	{idE: "1", idC:"3", idKET: "3", name: "MATERIALES BIOACTIVOS"},
	{idE: "1", idC:"3", idKET: "4", name: "POLÍMEROS DE LIBERACIÓN DE DROGAS"},
	{idE: "1", idC:"3", idKET: "5", name: "BIOCHIPS"},
	{idE: "1", idC:"3", idKET: "6", name: "BIOMIMETICA"},
	{idE: "1", idC:"3", idKET: "7", name: "MATERIALES BIOSENSOR"},
	{idE: "1", idC:"4", idKET: "1", name: "MATERIALES PIEZOELÉCTRICOS"},
	{idE: "1", idC:"4", idKET: "2", name: "MATERIALES MAGNETOSTRICTIVOS"},
	{idE: "1", idC:"4", idKET: "3", name: "MEMORIA DE FORMAS DE POLIMEROS Y ALEACIONES"},
	{idE: "1", idC:"4", idKET: "4", name: "MATERIALES FERROELECTRICOS"},
	{idE: "1", idC:"4", idKET: "5", name: "MATERIALES SUPERCONDUCTIVOS"},
	{idE: "1", idC:"4", idKET: "6", name: "METAMATERIALES"},
	{idE: "2", idC:"1", idKET: "1", name: "TECNOLOGIAS DE LA MICROBIOLOGIA"},
	{idE: "2", idC:"1", idKET: "2", name: "NANOBIOINGENIERIA"},
	{idE: "2", idC:"1", idKET: "3", name: "NANOBIOMATERIALES"},
	{idE: "2", idC:"1", idKET: "4", name: "COMPUTACIÓN BIOMÉDICA Y BIOINFORMÁTICA"},
	{idE: "2", idC:"2", idKET: "1", name: "DISPOSITIVOS MEDICOS AVANZADOS"},
	{idE: "2", idC:"2", idKET: "2", name: "BIOROBOTICA"},
	{idE: "2", idC:"2", idKET: "3", name: "IMAGEN BIOMEDICA"},
	{idE: "2", idC:"2", idKET: "4", name: "BIONICA"},
	{idE: "2", idC:"3", idKET: "1", name: "MEDICINA PERSONALIZADA"},
	{idE: "2", idC:"3", idKET: "2", name: "MEDICINA REGENERATIVA"},
	{idE: "2", idC:"3", idKET: "3", name: "NUEVAS TERAPIAS PARA LAS ENFERMEDADES CRONICAS"},
	{idE: "2", idC:"3", idKET: "4", name: "ICT PARA LA SALUD"},
	{idE: "2", idC:"4", idKET: "1", name: "FARMANANOTECNOLOGIA"},
	{idE: "2", idC:"4", idKET: "2", name: "BIOFARMACÉUTICOS E INGENIERÍA DE VACUNAS"},
	{idE: "2", idC:"4", idKET: "3", name: "TECNOLOGÍAS DE TOXICIDAD FARMACÉUTICA"},
	{idE: "2", idC:"5", idKET: "1", name: "TECNOLOGÍA DE LOS ALIMENTOS"},
	{idE: "2", idC:"5", idKET: "2", name: "TECNOLOGÍA DE LA AGRICULTURA"},
	{idE: "2", idC:"5", idKET: "3", name: "TECNOLOGÍAS DE PESCA Y ECOSISTEMAS ACUÁTICOS"},
	{idE: "2", idC:"5", idKET: "4", name: "SALUD ANIMAL"},
	{idE: "3", idC:"1", idKET: "1", name: "BIOMETRICAS"},
	{idE: "3", idC:"1", idKET: "2", name: "PAGO ELECTRONICO"},
	{idE: "3", idC:"1", idKET: "3", name: "DELITO CIBERNETICO"},
	{idE: "3", idC:"2", idKET: "1", name: "ANALISIS DE DATOS"},
	{idE: "3", idC:"2", idKET: "2", name: "COMPUTACIÓN EN LA NUBE"},
	{idE: "3", idC:"2", idKET: "3", name: "HTML5"},
	{idE: "3", idC:"2", idKET: "4", name: "BYOD Y APLICACIONES SIN FRONTERAS"},
	{idE: "3", idC:"3", idKET: "1", name: "GEOLOCALIZACION, POSICIONAMIENTO INTERIOR Y EXTERIOR Y MAPEO DIGITAL"},
	{idE: "3", idC:"3", idKET: "2", name: "REDES 3G Y 4G"},
	{idE: "3", idC:"3", idKET: "3", name: "APLICACIONES PARA TABLETS Y SMARTPHONES"},
	{idE: "3", idC:"3", idKET: "4", name: "ANTENAS INTELIGENTES"},
	{idE: "3", idC:"3", idKET: "5", name: "SENSOR DE REDES INALÁMBRICAS (WSN)"},
	{idE: "3", idC:"4", idKET: "1", name: "REDES NEURONALES Y MOTORES DE BÚSQUEDA SEMÁNTICA"},
	{idE: "3", idC:"4", idKET: "2", name: "INTERACCION HUMANO-MAQUINA"},
	{idE: "3", idC:"4", idKET: "3", name: "ROBOTICA AVANZADA"},
	{idE: "3", idC:"4", idKET: "4", name: "COMPUTACIÓN CUÁNTICA"},
	{idE: "3", idC:"5", idKET: "1", name: "REALIDAD AUMENTADA (AR) Y VIRTUALIZACION"},
	{idE: "3", idC:"5", idKET: "2", name: "GAMIFICACION"},
	{idE: "3", idC:"5", idKET: "3", name: "APRENDIZAJE ELECTRÓNICO"},
	{idE: "3", idC:"5", idKET: "4", name: "REDES SOCIALES"},
	{idE: "4", idC:"1", idKET: "1", name: "LIGERO Y AERODINAMICO"},
	{idE: "4", idC:"1", idKET: "2", name: "EV"},
	{idE: "4", idC:"1", idKET: "3", name: "VEHICULOS HIBRIDOS"},
	{idE: "4", idC:"2", idKET: "1", name: "BIODIESEL"},
	{idE: "4", idC:"2", idKET: "2", name: "BIOCOMBUSTIBLE AVANZADOS"},
	{idE: "4", idC:"2", idKET: "3", name: "CALOR Y POTENCIA COMBINADOS (CHP)"},
	{idE: "4", idC:"2", idKET: "4", name: "BIOCALEFACCION"},
	{idE: "4", idC:"3", idKET: "1", name: "ILUMINACIÓN"},
	{idE: "4", idC:"3", idKET: "2", name: "GESTIÓN DEL HOGAR E INSTALACIONES ENERGÉTICAS"},
	{idE: "4", idC:"3", idKET: "3", name: "ELECTRODOMESTICOS INTELIGENTES"},
	{idE: "4", idC:"3", idKET: "4", name: "GESTIÓN DE LA ENERGIA INDUSTRIAL"},
	{idE: "4", idC:"3", idKET: "5", name: "CALEFACCIÓN Y REFRIGERACIÓN EFICIENTE"},
	{idE: "4", idC:"4", idKET: "1", name: "GESTIÓN, MEDICIÓN Y CONTROL DE LA ENERGIA"},
	{idE: "4", idC:"4", idKET: "2", name: "CONTADORES INTELIGENTES"},
	{idE: "4", idC:"4", idKET: "3", name: "INFRAESTRUCTURA DE CARGA"},
	{idE: "4", idC:"4", idKET: "4", name: "MICROREJILLAS"},
	{idE: "4", idC:"5", idKET: "1", name: "PV SOLAR"},
	{idE: "4", idC:"5", idKET: "2", name: "ENERGÍA SOLAR CONCENTRADA (CSP)"},
	{idE: "4", idC:"5", idKET: "3", name: "VIENTO"},
	{idE: "4", idC:"5", idKET: "4", name: "GEOTERMICO"},
	{idE: "4", idC:"5", idKET: "5", name: "BIOMASAS"},
	{idE: "4", idC:"5", idKET: "6", name: "MARINOS RENOVABLES"},
	{idE: "4", idC:"6", idKET: "1", name: "ION DE LITIO"},
	{idE: "4", idC:"6", idKET: "2", name: "METAL DE AIRE"},
	{idE: "4", idC:"6", idKET: "3", name: "CELDAS DE COMBUSTIBLE"},
	{idE: "4", idC:"6", idKET: "4", name: "MEGA CAPACITORES"},
	{idE: "4", idC:"6", idKET: "5", name: "BATERIAS DE FLUJO REDIOX"},
	{idE: "5", idC:"1", idKET: "1", name: "TRATAMIENTO BIOLOGICO MECANICO DE RESIDUOS SOLIDOS MUNICIPALES"},
	{idE: "5", idC:"1", idKET: "2", name: "GASIFICACIÓN POR PLASMA"},
	{idE: "5", idC:"1", idKET: "3", name: "RECICLAJE DE RESIDUOS"},
	{idE: "5", idC:"1", idKET: "4", name: "RELLENO SANITARIO BIOREACTOR"},
	{idE: "5", idC:"1", idKET: "1", name: "SEMILLAS Y PROPAGACION"},
	{idE: "5", idC:"1", idKET: "2", name: "PROXIMA GENERACION DE FERTILIZANTES"},
	{idE: "5", idC:"1", idKET: "3", name: "CULTIVO Y POST DE LA COSECHA."},
	{idE: "5", idC:"1", idKET: "4", name: "PROTECCIÓN DE CULTIVOS"},
	{idE: "5", idC:"1", idKET: "5", name: "INVERNADERO"},
	{idE: "5", idC:"1", idKET: "1", name: "FILTRACION DE AGUA"},
	{idE: "5", idC:"1", idKET: "2", name: "INFRAESTRUCTURA Y DISTRIBUCION HIDRICA"},
	{idE: "5", idC:"1", idKET: "3", name: "IRRIGACIÓN"},
	{idE: "5", idC:"1", idKET: "4", name: "VALOR AGREGADO A LOS RECURSOS HIDRICOS"},
	{idE: "5", idC:"1", idKET: "5", name: "COSECHA DE AGUA"},
	{idE: "5", idC:"1", idKET: "6", name: "IDENTIFICACIÓN DE RECURSOS HIDRICOS"},
	{idE: "5", idC:"1", idKET: "1", name: "PROCESOS DE AGUA INDUSTRIALES Y PRODUCIDOS."},
	{idE: "5", idC:"1", idKET: "2", name: "DESALINIZACIÓN"},
	{idE: "5", idC:"1", idKET: "3", name: "DESINFECCIÓN DEL AGUA"},
	{idE: "5", idC:"1", idKET: "4", name: "PUNTO DE USO DE TRATAMIENTO DE AGUAS"},
	{idE: "5", idC:"1", idKET: "5", name: "TRATAMIENTO DE AGUAS RESIDUALES (ALCANTARILLADO)"},
	{idE: "5", idC:"1", idKET: "1", name: "EFICIENCIA DE RECURSOS EN EDIFICIOS"},
	{idE: "5", idC:"1", idKET: "2", name: "CALIDAD INTERNA DEL AIRE"},
	{idE: "5", idC:"5", idKET: "3", name: "EFICIENCIA DE LA ENERGÍA EN EDIFICIOS"},
	{idE: "5", idC:"5", idKET: "4", name: "MATERIALES BIOBASADOS VERDES"},
	{idE: "5", idC:"6", idKET: "1", name: "CAPTURA Y ALMACENAMIENTO DE CARBONO (CCS) Y USO Y ALMACENAMIENTO DE CAPTURA DE CARBONO (CCUS)"},
	{idE: "5", idC:"6", idKET: "2", name: "CONVERSOR CATALÍTICO"},
	{idE: "5", idC:"6", idKET: "3", name: "SISTEMAS DE ESCRITURA"},
	{idE: "5", idC:"6", idKET: "4", name: "MONITOREO DE EMISIONES"}
];