export default [
	{idE: "1", idC:"1", name: "SEMICONDUCTORES, MATERIALES ELECTRONICOS Y MAGNETICOS"},
	{idE: "1", idC:"2", name: "MATERIALES NANOESTRUCTURADOS"},
	{idE: "1", idC:"3", name: "BIOMATERIALES"},
	{idE: "1", idC:"4", name: "MATERIALES FUNCIONALES E INTELIGENTES"},
	{idE: "2", idC:"1", name: "BIOINGENIERIA"},
	{idE: "2", idC:"2", name: "DISPOSITIVOS MEDICOS"},
	{idE: "2", idC:"3", name: "MEDICINA FUTURA"},
	{idE: "2", idC:"4", name: "TECNOLOGIAS FARMACEUTICAS"},
	{idE: "2", idC:"5", name: "TECNOLOGIAS DE ALIMENTOS AGRI"},
	{idE: "3", idC:"1", name: "SEGURIDAD TI"},
	{idE: "3", idC:"2", name: "BIG DATA, SOFTWARE EMPRESARIAL Y NUEVOS LENGUAJES"},
	{idE: "3", idC:"3", name: "MOVILES Y COMUNICACIONES"},
	{idE: "3", idC:"4", name: "INTELIGENCIA ARTIFICIAL"},
	{idE: "3", idC:"5", name: "REDES Y VIDA DIGITAL"},
	{idE: "4", idC:"1", name: "AUTOMOTRIZ Y TRANSPORTE"},
	{idE: "4", idC:"2", name: "BIOENERGIA"},
	{idE: "4", idC:"3", name: "EFICIENCIA ENERGÉTICA"},
	{idE: "4", idC:"4", name: "REJILLAS Y REJILLAS INTELIGENTES"},
	{idE: "4", idC:"5", name: "ENERGIA RENOVABLE"},
	{idE: "4", idC:"6", name: "ALMACENAMIENTO DE ENERGÍA ELÉCTRICA (EES)"},
	{idE: "5", idC:"1", name: "RESIDUOS DE RECURSOS"},
	{idE: "5", idC:"2", name: "TECNOLOGIA AGRI"},
	{idE: "5", idC:"3", name: "RECURSOS Y ENTREGA HIDRICA"},
	{idE: "5", idC:"4", name: "TRATAMIENTO Y PURIFICACION HIDRICA"},
	{idE: "5", idC:"5", name: "EDIFICIOS SUSTENTABLES"},
	{idE: "5", idC:"6", name: "CONTROL DE CONTAMINACION DEL AIRE"}
];