export default [
	{id: "11", value:"El trabajo del proyecto va más allá de la investigación básica y se ha definido el concepto de la tecnología "}	,
	{id:"12", value:"La investigación aplicada ha comenzado y la (s) aplicación (es) práctica (s) han sido identificadas"},
	{id:"13", value:"Han comenzado las pruebas preliminares de los componentes tecnológicos y se ha establecido la viabilidad técnica en un  ambiente de laboratorio"},
	{id:"14", value:"Las pruebas iniciales del prototipo / sistema integrado se han completado en un entorno de laboratorio"},
	{id:"15", value:"El producto / sistema integrado a escala de laboratorio demuestra el rendimiento en la (s) aplicación (es) deseada (s)"},
	{id:"16", value:"Prototipo industrial / sistema para ensayos en entorno operacional real"},
	{id:"17", value:"El prototipo /sistema se da por probado y funciona. Se certifica la tecnología según las normas del mercado donde vaya a operar"},
	{id:"18", value:"Lanzamiento del nuevo producto "},
	{id:"21", value:"No se tiene identificado aún."},
	{id:"22", value:"El producto / mercado inicial ha sido definido"},
	{id:"23", value:"El producto / sistema a escala piloto ha sido probado en la (s) aplicación (es) deseada (s) "},
	{id:"24", value:"La demostración de un prototipo de producto / sistema a escala completa se ha completado en la (s) aplicación (es) deseada (s)"},
	{id:"25", value:"Se ha comprobado que el producto / sistema real funciona en su forma casi final bajo un conjunto representativo de condiciones y entornos esperados"},
	{id:"26", value:"El producto / sistema está en forma final y ha sido operado bajo la gama completa de condiciones y ambientes operativos"},
	{id:"31", value:"No se tiene identificado aún."},
	{id:"32", value:"Se han definido una o más hipótesis iniciales del producto"},
	{id:"33", value:"La asignación de los atributos del producto / sistema a las necesidades del cliente ha resaltado una propuesta de valor clara"},
	{id:"34", value:"El producto / sistema ha sido escalado de laboratorio a escala piloto y los problemas que pueden afectar el logro de una escala completa han sido identificados"},
	{id:"35", value:"Se desarrolló un modelo integral de propuesta de valor para el cliente, que incluye una comprensión detallada del producto / sistema con especificaciones de diseño, certificaciones requeridas y compensaciones."},
	{id:"36", value:"La optimización del diseño final del producto / sistema se ha completado, se han obtenido las certificaciones requeridos y el producto / sistema ha incorporado requisitos detallados de los clientes y productos."},
	{id:"41", value:"No se tiene identificado aún."},
	{id:"42", value:"Se realizó una investigación de mercado secundaria y el conocimiento básico de aplicaciones potenciales y el panorama competitivo ha sido identificado."},
	{id:"43", value:"Se ha completado la investigación de mercado principal para probar la viabilidad comercial del producto / sistema y la comprensión básica de productos / sistemas competitivos han sido demostrados."},
	{id:"44", value:"Se ha completado una exhaustiva investigación de mercado para comprobar la viabilidad comercial del producto / sistema y se ha demostrado una comprensión intermedia de los productos / sistemas de la competencia."},
	{id:"45", value:"Se completó un análisis competitivo para ilustrar las características y ventajas únicas del producto / sistema en comparación con los productos / sistemas de la competencia."},
	{id:"46", value:"Se ha logrado una comprensión total y completa del panorama competitivo, la (s) aplicación (es) de destino, los productos / sistemas competitivos y el mercado."},
	{id:"51", value:"No se tiene identificado aún."},
	{id:"52", value:"Ningún equipo o compañía en el lugar (persona natural, ninguna entidad legal)"},
	{id:"53", value:"Fundadores únicamente técnicos o no técnicos que dirigen la empresa sin asistencia externa"},
	{id:"54", value:"Fundadores únicamente técnicos o no técnicos que dirigen la empresa con ayuda de asesores externos / mentores y / o incubadora / aceleradora"},
	{id:"55", value:"Equipo equilibrado con experiencia en desarrollo / comercialización técnica y comercial al cargo de la empresa con la asistencia de asesores externos / mentores"},
	{id:"56", value:"Equipo equilibrado con todas las capacidades a bordo (por ejemplo, ventas, marketing, servicio al cliente, operaciones, etc.) dirigiendo la empresa con asistencia de asesores externos / mentores"},
	{id:"61", value:"No se tiene identificado aún."},
	{id:"62", value:"El modelo de negocio inicial y la propuesta de valor han sido definidos."},
	{id:"63", value:"Los clientes / socios han sido entrevistados para comprender sus puntos / necesidades de dolor, y el modelo comercial y la propuesta de valor han sido refinados en base a los comentarios de los clientes / socios."},
	{id:"64", value:"Se han definido las necesidades del mercado y del cliente / socio y cómo se traducen a los requisitos del producto, y se han desarrollado relaciones iniciales con los principales interesados ​​en toda la cadena de valor."},
	{id:"65", value:"Se han formado asociaciones con partes interesadas clave en toda la cadena de valor (por ejemplo, proveedores, socios, proveedores de servicios y clientes)"},
	{id:"66", value:"Se han establecido acuerdos de suministro con proveedores y socios y se han recibido las órdenes de compra iniciales de los clientes."},
	{id:"71", value:"No se tiene identificado aún."},
	{id:"72", value:"Se identificaron y mapearon posibles proveedores, socios y clientes en un análisis inicial de la cadena de valor"},
	{id:"73", value:"Se establecieron relaciones con posibles proveedores, socios, proveedores de servicios y clientes, y se proporcionaron comentarios sobre los requisitos del producto y la capacidad de fabricación."},
	{id:"74", value:"Las calificaciones del proceso de fabricación (por ejemplo, QC / QA) se han definido y están en progreso"},
	{id:"75", value:"Los productos / sistemas se han fabricado y vendido a clientes iniciales"},
	{id:"76", value:"Se ha logrado la fabricación a gran escala y el despliegue generalizado de producto / sistema a clientes y / o usuarios."},
	{id:"81", value:"No se tiene identificado aún."},
	{id:"82", value:"Licencia o Cesión de la Tecnología/Desarrollo "},
	{id:"83", value:"Explotación Directa "},
	{id:"91", value:"La investigación aplicada ha comenzado y la (s) aplicación (es) práctica (s) han sido identificadas"},
	{id:"92", value:"Han finalizado las pruebas preliminares de los componentes tecnológicos y se ha establecido la viabilidad técnica en un  ambiente de laboratorio"},
	{id:"93", value:"Las pruebas iniciales del prototipo / sistema integrado se han completado en un entorno de laboratorio"},
	{id:"94", value:"El producto / sistema integrado a escala de laboratorio demuestra el rendimiento en la (s) aplicación (es) deseada (s)"},
	{id:"95", value:"Prototipo industrial / sistema para ensayos en entorno operacional real"},
	{id:"96", value:"El prototipo /sistema se da por probado y funciona. Se certifica la tecnología según las normas del mercado donde vaya a operar"},
	{id:"97", value:"Lanzamiento del nuevo producto "},
	{id:"101", value:"Apoyo financiero"},
	{id:"102", value:"Acompañamiento en la formulación del proyecto"},
	{id:"103", value:"Acceso a nuevos mercados "},
	{id:"104", value:"Personal Capacitado y/o Talento Humano"},
	{id:"105", value:"Jurídico - Legal"},
	{id:"106", value:"Otro (describir)"},
];